# Generated by Django 5.1.4 on 2024-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='series',
            name='rating',
        ),
        migrations.AddField(
            model_name='series',
            name='episodes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(upload_to='series/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='seasons',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='series',
            name='year',
            field=models.IntegerField(),
        ),
    ]
